version: '3'

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE:      parrot-wings
            MYSQL_USER:          user
            MYSQL_PASSWORD:      password
            MYSQL_ROOT_PASSWORD: toor

    php:
        build:
            context:    .
            dockerfile: docker/php/Dockerfile
        working_dir: /app
        environment:
            WAIT_FOR_MYSQL_TIMEOUT: ~
            DATABASE_URL:           mysql://user:password@mysql/parrot-wings
            MERCURE_PUBLISH_URL:    http://mercure/.well-known/mercure
        links:
            - mysql
        depends_on:
            - mysql
        ports:
            - ${BACKEND_PORT}:8000

    frontend:
        build:
            context:    .
            dockerfile: docker/frontend/Dockerfile
        working_dir: /app
        environment:
            REACT_APP_API_URL: http://localhost:${BACKEND_PORT}
        links:
            - php
        depends_on:
            - php
        ports:
            - ${FRONTEND_PORT}:3000


    mercure:
        image: dunglas/mercure
        environment:
            JWT_KEY: ${MERCURE_SECRET}
        ports:
            - ${MERCURE_PORT}:80
